GET /users HTTP/1.1
Host: localhost:8080

POST /cars HTTP/1.1
Host: localhost:8080
Content-Type: application/json
{
    "marca":         "Mazda",
    "referencia":     "CX-30",
    "modelo":         "2023",
    "tipo":           "SUV",
    "potencia":       "180 HP",
    "torque":         "200 Nm",
    "transmision":    "Automatica",
    "motor":          "2.5L",
    "pasajeros":      "7Pasajeros",
    "combustible":    "Extra",
    "consumo":        "Elevado",
    "almacenamiento": "Elevado",
    "descripcion":    "Que chimba de carro",
    "lujo":           1,
    "deportivo":      0,
    "imagen":         "Holaaaa"
}